app/routes/frontend_routes.py
# app/routes/frontend_routes.py
from flask import Blueprint, flash, jsonify, make_response, redirect, render_template, request, url_for, session
from flask_jwt_extended import set_access_cookies, jwt_required, get_jwt_identity
import requests
from app.config import BASE_URL

from app.forms import LoginForm, SignupForm


frontend_blueprint = Blueprint('frontend', __name__, url_prefix='/')


@frontend_blueprint.route('/')
def index():
    return "Hello world"


@frontend_blueprint.route('/about')
def about():
    return "About us"


@frontend_blueprint.route('/login', methods=['GET', 'POST'])
def login():
    user = None
    form = LoginForm()
    if form.validate_on_submit():
        # Create a JSON object with the user credentials
        user_data = {
            "username": form.username.data,
            "password": form.password.data
        }
        print(user_data)
        # Send a POST request to the local Flask endpoint `/api/user/login`
        headers = {'Content-Type': 'application/json'}
        login_url = f"{BASE_URL}/api/user/login"
        response = requests.post(login_url, json=user_data)
        print(response)

        # If the login is successful, store the JWT authorization token in a cookie
        if response.status_code == 200:
            # Authentication successful, store the JWT token in a cookie
            jwt_token = response.json().get('jwt_token')
            session['jwt_token'] = jwt_token

            return redirect(url_for('frontend.dashboard'))
        # If the login is unsuccessful, prompt the user that the login credentials are incorrect
        elif response.status_code == 401:
            flash('Incorrect login credentials.')

    return render_template("log_in.html", form=form, user=user)

@frontend_blueprint.route('/logout', methods=['GET', 'POST'])
def logout():
    session.pop('jwt_token', None)
    return redirect(url_for('frontend.login'))

@frontend_blueprint.route('sign_up', methods=['POST', 'GET'])
def sign_up():
    form = SignupForm()
    if form.validate_on_submit():
        user_data = {
            "username": form.username.data,
            "email": form.email.data,
            "password": form.password.data,
            "first_name": form.first_name.data,
            "last_name": form.last_name.data,
            "date_of_birth": str(form.date_of_birth.data)
        }
        register_url = f"{BASE_URL}/api/user/register"
        response = requests.post(register_url, json=user_data)
        print(response)

        if response.status_code == 201:
            flash('You have successfully signed up!')
            redirect(url_for('frontend.login'))
        else:
            flash('Something went wrong. Please try again.')
            redirect(url_for('frontend.sign_up'))
    return render_template("sign_up.html", form=form)


@frontend_blueprint.route('dashboard', methods=['POST', 'GET'])
def dashboard():
    user = None
    jwt_token = f"Bearer {session.get('jwt_token')}"
    profile_url = f"{BASE_URL}/api/user/profile"
    response = requests.get(profile_url,headers={"Authorization": jwt_token})
    print(response)
    if response.status_code == 200:
        user = response.json()
        print(user)

    return render_template("home_dashboard.html", user=user)


@frontend_blueprint.route('/profile', methods=['POST', 'GET'])
def profile():
    return render_template("profile.html")


@frontend_blueprint.route('/bills', methods=['POST', 'GET'])
def bills():
    return render_template("bills.html")


@frontend_blueprint.route('savings', methods=['POST', 'GET'])
def savings():
    return render_template("savings.html")

app/templates/_sidebar.html
<!-- Sidebar -->
<div class="col-md-3">
  <div class="sidebar">
    <div class="sidebar-header">
      <h1>LilFedha</h1>
    </div>
    <!-- Add sidebar navigation links if needed -->
    <div class="sidebar-menu">
      <a href="{{ url_for('frontend.dashboard') }}" style="text-decoration: none;"><button class="btn btn-link text-center">Home</button></a>
      <a href="{{ url_for('frontend.bills') }}" style="text-decoration: none;"><button class="btn btn-link text-center">Bills</button></a>
      <a href="{{ url_for('frontend.savings') }}" style="text-decoration: none;"><button class="btn btn-link text-center">Savings</button></a>
      <a href="{{ url_for('frontend.logout') }}" style="text-decoration: none;"><button class="btn btn-link text-center">Logout</button></a>

      {# <a href="#"><button class="btn btn-link text-center">Investments</button></a> #}
    </div>
  </div>
</div>

app/templates/base.html
<!doctype html>
<html lang="GB">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.rtl.min.css" integrity="sha384-nU14brUcp6StFntEOOEBvcJm4huWjB0OcIeQ3fltAfSmuZFrkAif0T+UtNGlKKQv" crossorigin="anonymous">
    {% block stylesheets %} {% endblock %}

    <title>{% block title %}{% endblock %} | LiL fedha</title>
  </head>
  <body>

    <div class="container">
      {% for message in get_flashed_messages() %}
        <div class="alert alert-warning">
          {{ message }}
        </div>
      {% endfor %}
    </div>
    {% block content %}

    {% endblock %}


    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.min.js" integrity="sha384-BBtl+eGJRgqQAUMxJ7pMwbEyER4l1g+O15P+16Ep7Q9Q+zqX6gSbd85u4mG4QzX+" crossorigin="anonymous"></script>
    -->
  </body>
</html>

app/templates/bills.html
{% extends 'dashboard.html' %}

{# {% include '_sidebar.html' %} #}
{% block stylesheets %}
  <link rel="stylesheet" href="{{ url_for('static', filename = 'css/bills.css') }}" />
{% endblock %}

{% block dashboard_content %}
  <div class="col-md-9 ml-md-auto">
    <div class="dashboard-content">
      <h2>Add your Monthly bills</h2>
      <table class="bills-table">
        <thead>
          <tr>
            <th>Name</th>
            <th>Amount</th>
            <th>Date Due</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td>
              <input type="text" name="billName[]" placeholder="Enter bill name" />
            </td>
            <td>
              <input type="number" name="billAmount[]" placeholder="Enter amount" />
            </td>
            <td>
              <input type="date" name="billDueDate[]" />
            </td>
          </tr>
          <tr>
            <td>
              <input type="text" name="billName[]" placeholder="Enter bill name" />
            </td>
            <td>
              <input type="number" name="billAmount[]" placeholder="Enter amount" />
            </td>
            <td>
              <input type="date" name="billDueDate[]" />
            </td>
          </tr>
          <tr>
            <td>
              <input type="text" name="billName[]" placeholder="Enter bill name" />
            </td>
            <td>
              <input type="number" name="billAmount[]" placeholder="Enter amount" />
            </td>
            <td>
              <input type="date" name="billDueDate[]" />
            </td>
          </tr>
        </tbody>
      </table>
      <button id="addBillButton">Add</button>
      <button id="removeBillButton">Remove</button>
      <button id="createBudgetButton" class="budget-button">Create Budget</button>
    </div>
  </div>
  <script src="{{ url_for('static', filename = 'js/bills.js') }}"></script>
{% endblock %}

app/templates/dashboard.html
{% extends 'base.html' %}
{% block title %}
  Dashboard
{% endblock %}

{% block stylesheets %}

{% endblock %}

{% block content %}
  <div class="container">
    <div class="row">
      <!-- Sidebar -->
      {# <div class="sidebar">
          <div class="sidebar-header">
            <h1>LilFedha</h1>
          </div>
          <!-- Add sidebar navigation links if needed -->
          <div class="sidebar-menu">
            <a href="#"><button class="btn btn-link text-center">Home</button></a>
            <a href="{{ url_for('frontend.bills') }}"><button class="btn btn-link text-center">Bills</button></a>
            <a href="#"><button class="btn btn-link text-center">Savings</button></a>
            <a href="#"><button class="btn btn-link text-center">Investments</button></a>
          </div>
        </div>#}
      {% include '_sidebar.html' %}

      <div class="">
        <div class="dashboard-content">
          {% block dashboard_content %}

          {% endblock %}
          {# <div class="charts">
              <div class="pie-chart">
                <!-- Add your pie chart content here -->
              </div>
              <div class="line-chart">
                <!-- Add your line chart content here -->
              </div>
            </div>
            <div class="expense-table">
              <!-- Add your expense table content here -->
              <table>
                <!-- Table content here -->
              </table>
            </div>#}
        </div>
      </div>
    </div>
  </div>
{% endblock %}

app/templates/home_dashboard.html
{% extends 'dashboard.html' %}

{% block stylesheets %}
  <link rel="stylesheet" href="{{ url_for('static', filename = 'css/dashboard.css') }}" />
{% endblock %}
{% block dashboard_content %}
  <div class="finance-summary">
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <nav class="navbar bg-body-tertiary">
            <div class="container-fluid">
              {# <a class="navbar-brand" href="#">Fixed top</a> #}
              <h1>Welcome {{ user.username }}!!! 🎉</h1>
            </div>
          </nav>
          <br />
          <h4>Your daily progress</h4>
          <div class="row">
            <div class="col-sm-6 mb-3 mb-sm-0">
              <div class="card">
                <div class="card-body">
                  <h5 class="card-title">Check your current bills</h5>
                  <p class="card-text">With supporting text below as a natural lead-in to additional content.</p>
                  <a href="#" class="btn btn-primary">Check</a>
                </div>
              </div>
            </div>
            <div class="col-sm-6">
              <div class="card">
                <div class="card-body">
                  <h5 class="card-title">Check your current savings</h5>
                  <p class="card-text">With supporting text below as a natural lead-in to additional content.</p>
                  <a href="#" class="btn btn-primary">Check</a>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

app/templates/log_in.html
{% import "bootstrap/wtf.html" as wtf %}
{% extends "base.html" %}

{% block stylesheets%}
    <link rel="stylesheet" href="{{ url_for('static', filename='css/log_in.css') }}">
{% endblock %}

{% block title %}{{ super() }}Login{% endblock %}

{% block navbar %} {% endblock %}

{% block content %}
    <div class="container">
        <div class="form-container p-4 border rounded">
            <h2 class="text-center mb-4">Log In</h2>
                <form action="" method="post">
                    {{ form.hidden_tag() }}

                    {{ wtf.form_field(form.username) }}
                    {{ wtf.form_field(form.password) }}
                    {{ wtf.form_field(form.remember_me) }}
                    {{ wtf.form_errors(form, hiddens='only') }}
                    <div class="text-center">
                        <button type='{{ form.submit }}' class="btn btn-primary">
                            Log In
                        </button>
                    </div>
                </form>
                <div class="mt-3 text-center">
                    <p>Don't have an account? <a href="{{ url_for('frontend.sign_up') }}">Sign up</a></p>
                </div>
        </div>
    </div>
{% endblock %}

app/templates/savings.html
{% extends 'dashboard.html' %}

{# {% include '_sidebar.html' %} #}
{% block stylesheets %}
  <link rel="stylesheet" href="{{ url_for('static', filename = 'css/savings.css') }}" />
{% endblock %}

{% block dashboard_content %}
  <div class="encouragement">
    <p>Start your journey to financial freedom by saving. Saving regularly can help you achieve your financial goals faster. Let's get started!</p>
  </div>

  <div class="savings-form">
    <h2>Create a Savings Plan</h2>
    <form>
      <div class="form-group">
        <label for="planName">Plan Name</label>
        <input type="text" id="planName" name="planName" placeholder="Enter plan name" required />
      </div>
      <div class="form-group">
        <label for="monthlyContribution">Monthly Contribution</label>
        <input type="number" id="monthlyContribution" name="monthlyContribution" placeholder="Enter amount" required />
      </div>
      <div class="form-group">
        <label for="dueDate">Due Date</label>
        <input type="date" id="dueDate" name="dueDate" required />
      </div>
      <div class="form-group">
        <label for="duration">Duration (in months)</label>
        <input type="number" id="duration" name="duration" placeholder="Enter duration" required />
      </div>
      <button id="createPlanButton" class="create-button">Create Plan</button>
    </form>
  </div>
{% endblock %}

app/templates/sign_up.html
{% import "bootstrap/wtf.html" as wtf %}
{% extends "base.html" %}

{% block title %}Sign Up{% endblock %}


{% block stylesheets%}
    <link rel="stylesheet" href="{{ url_for('static', filename='css/sign_up.css') }}">
{% endblock %}

{% block content %}
    <div class="container">
        <div class="form-container p-4 border rounded">
            <h2 class="text-center mb-4">Sign Up</h2>
                <form action="" method="post">
                    {{ form.hidden_tag() }}
                    <div class="mb-3">
                        {{ wtf.form_field(form.username) }}
                    </div>
                    {{ wtf.form_field(form.first_name) }}
                    {{ wtf.form_field(form.last_name) }}
                    {{ wtf.form_field(form.email) }}
                    {{ wtf.form_field(form.password) }}
                    {{ wtf.form_field(form.repeat_password) }}
                    <div class="text-center">
                        <button type='{{ form.submit }}' class="btn btn-primary">
                            Log In
                        </button>
                    </div>
                </form>
                <div class="mt-3 text-center">
                    <p>Already an account? <a href="{{ url_for('frontend.login') }}">Login</a></p>
                </div>
        </div>
    </div>

{% endblock%}